* An .emacs.d

#+BEGIN_QUOTE
Cyberspace. A consensual hallucination experienced daily by billions of
legitimate operators, in every nation, by children being taught mathematical
concepts... A graphic representation of data abstracted from banks of every
computer in the human system. Unthinkable complexity. Lines of light ranged in
the nonspace of the mind, clusters and constellations of data. Like city
lights, receding...

--- William Gibson, /Neuromancer/
#+END_QUOTE

#+BEGIN_QUOTE
"Because keyboards are accessories to PC makers, they focus on minimizing the
manufacturing costs. But that's incorrect. When America's cowboys were in the
middle of a trip and their horse died, they would leave the horse there. But
even if they were in the middle of a desert, they would take their saddle with
them. The horse was a consumable good, but the saddle was an interface that
their bodies had gotten used to. In the same vein, PCs are consumable goods,
while keyboards are important interfaces."

--- Professor Eiiti Wada
#+END_QUOTE
